### ISSUE TITLE
Stale auth tokens on epic

### ISSUE THREAD

**Issue by ARoese** [Chiv2-Community/C2GUILauncher#13]
After closing chivalry, (vanilla or modded) Epic users CANNOT launch again with the same auth tokens they just used. (in command line arguments) They MUST re-launch the launcher through epic to get new tokens, and the launcher should notify them of this fact after chiv is closed and prevent them from launching with stale args (by greying out the buttons and writing a note to them). 

Steam users are able to re-launch directly because they don't use any such auth in the command line arguments.

**Comment by Jacoby6000** [comment]
See #11
