### ISSUE TITLE
Load mods from registry

### ISSUE THREAD

**Issue by Jacoby6000** [Chiv2-Community/C2GUILauncher#3]
1. Create a registry repo on github
2. Create a sample mod and put it in the registry
3. Make the launcher read the registry and show a filterable mod list

Registry repo should have this structure, roughly.

* /
  * Readme.md 
  * mod-lists/
    * MyOrg

And "MyOrg" will contain a newline (\n) separated list of repositories which contain mods for the given org. eg:
```
# mod-lists/MyOrg
https://github.com/MyOrg/ExampleMod
```

Test cases should be written as a part of this ticket. I imagine the mod registry stuff will need tests more than most of the code.

**Comment by gimmic** [comment]
Could this just be another project in the Chiv2-Community org?
Like `Chiv2-Community/UnchainedMods`

**Comment by gimmic** [comment]
It looks like we're going to be capable of loading pak files directly. This helps potentially simplify mod repo and loading management. Distribution to clients of just a monolithic pak file will make things much more simple plus it could permit some baked-in dependency validation. (if the giantslayer mod needs a supporting mod, it can be baked in with the correct version for that mod).


Requirements:
- [ ] Pak files are included or built as part of repo listing approval. We would want to validate that:
  - the mod/pak source is available 
  - that the pak file listed is in fact built from the included source
- [ ] In support of versioning validation, if using pak distribution we could register the checksum of the pak file. This would be an easy sanity check and version match.
- [ ] It sounds like there is a load order challenge with pak files, so we may want to enforce that all modloader distributed paks are named specifically in the repo. Either `unchained-modname-version.pak` or `unchained-modname-filehash.pak` as examples.

**Comment by gimmic** [comment]
Mockup of metadata that might exist for packages listed in the repo:

```
[nihi/giantslayer]
description = Mod that adds Giant Slayer gamemode
version = 1.0
releasedate = 2023-07-31T20:54:37Z
tags = gamemode, nihi, multiplayer
pakfile = unchained-giantslayer.pak
pakfilehash = 349D1D1B577CFB257625D59BAB8DF197F1939AE333C89978D19EEE40C2A427F5
url = https://github.com/nihi/giantslayer
```

**Comment by Jacoby6000** [comment]
Heh, I didn't ever see your last comment. I think what we have now is sufficient though
