### ISSUE TITLE
Mod list display User Interactions

### ISSUE THREAD

**Issue by Jacoby6000** [Chiv2-Community/C2GUILauncher#8]
Leveraging #3 and and #7, display mods from the registry and make it so that users can select mods for download. It should default to the latest version but allow players to select older versions.

**Comment by gimmic** [comment]
- [ ] Refreshing the modlist user experience is good
- [ ] Showing what mods are currently Available / Installed / Enabled or Disabled
- [ ] Showing what local mods may be out of date and need updating (update now button)
- [ ] Show Mod Information from repo/link to details
- [ ] Show Mod Version information
- [ ] Show Mod size on disk(?)
